name: Rust-ci

on:
    push:
        branches: [main]
    pull_request:

env:
    CARGO_TERM_COLOR: always
    SQLX_VERSION: 0.8.6
    SQLX_FEATURES: "rustls,postgres"
    APP_USER: app
    APP_USER_PWD: secret
    APP_DB_NAME: newsletter

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: postgres
                ports:
                    - 5432:5432
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - name: Install sqlx-cli
              run: |
                  cargo install sqlx-cli \
                    --version ${{ env.SQLX_VERSION }} \
                    --no-default-features \
                    --features ${{ env.SQLX_FEATURES }} \
                    --locked
            - uses: Swatinem/rust-cache@v2
            - run: cargo test
              name: Testing
            - name: Create app user in Postgres
              run: |
                  sudo apt-get install postgresql-client
                  CREATE_QUERY="CREATE USER ${APP_USER} WITH PASSWORD '${APP_USER_PWD}';"
                  PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${CREATE_QUERY}"

                  GRANT_QUERY="ALTER USER ${APP_USER} CREATEDB;"
                  PGPASSWORD="password" psql -U "postgres" -h "localhost" -c "${GRANT_QUERY}"
            - run: SKIP_DOCKER=true ./scripts/init_db.sh
            - run: cargo test
            - run: cargo sqlx prepare --workspace --check -- --all-targets
    fmt:
        name: Check formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: Swatinem/rust-cache@v2
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt
            - run: cargo fmt -- --check
              name: Formatting

    clippy:
        name: Clippy
        runs-on: ubuntu-latest
        env:
            SQLX_OFFLINE: true
        steps:
            - uses: actions/checkout@v4
            - uses: Swatinem/rust-cache@v2
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy
            - run: cargo clippy -- -D warningsg
              name: Linting
